version: '3.8'
services:
  server: # Make sure the name of this service matches the name of your backend service in docker-compose.yml
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      FLASK_ENV: development
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    stdin_open: true # enables interactive mode, e.g., for hot reload tools
    tty: true # makes the container's console more interactive
    environment:
      NODE_ENV: production
